SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Orders;
TRUNCATE TABLE Arrangement;
TRUNCATE TABLE Employee;
TRUNCATE TABLE Customer;
TRUNCATE TABLE Flower;
TRUNCATE TABLE Accessory;

SET FOREIGN_KEY_CHECKS = 1;
